#!/usr/bin/env python3
"""Check/generate executable round trips of Move's exact public decoder bodies.

The fixtures independently follow the immutable original ABI schema. New
prepared entry points authenticate canonical typed private output; these tests
check preservation of every field, including numeric maxima and inactive tails.
They deliberately do not treat the decoder as a standalone untrusted parser.
"""
import argparse
import importlib.util
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
SPEC = importlib.util.spec_from_file_location('move_decoder_test_generator', HERE / 'generate-backend-move.py')
MOVE = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(MOVE)
DEST = HERE / 'noir-payload-tests'


def flatten_schema(schema):
    if schema['kind'] == 'array':
        return flatten_schema(schema['type']) * schema['length']
    if schema['kind'] == 'struct':
        return sum((flatten_schema(field['type']) for field in schema['fields']), [])
    return [schema]


def fixture(leaves, pattern):
    result = []
    for index, schema in enumerate(leaves):
        kind = schema['kind']
        if pattern == 'zero':
            value = 0
        elif kind == 'boolean':
            value = 1 if pattern == 'maximum' else index % 2
        elif kind == 'integer':
            bound = 1 << schema['width']
            value = bound - 1
            if pattern == 'mixed':
                value -= (index * 17) % min(bound, 257)
        else:
            value = -1 if pattern == 'maximum' else -(index + 1) * 18446744073709551617
        result.append(str(value))
    return '[' + ', '.join(result) + ']'


def generate():
    _, fragment, manifest = MOVE.build(MOVE.SNAPSHOT.read_text())
    backend_functions = MOVE.p.functions(fragment)
    schemas = MOVE.serialized_schema()
    source = '''// Generated by verify_move_payload_tests.py; decoder statements match Move exactly.
use aztec::protocol::{address::AztecAddress, traits::{Serialize, Deserialize, FromField}, utils::reader::Reader};
use libs::field_buffer::FieldBuffer;
use types::storage::{
    planet::{Planet, PlanetArtifacts, PlanetEvents, PlanetEventMetadata},
    arrival::Arrival, artifact::{Artifact, ArtifactLocation},
};

'''
    for variant, metadata in manifest['flatPreparedPayloads'].items():
        width = metadata['fields']
        source += f'unconstrained fn roundtrip_{variant}(prepared_payload: [Field; {width}]) {{'
        source += metadata['decode']
        for item in metadata['layout']:
            name, offset, length = item['name'], item['offset'], item['width']
            source += f'    let serialized_{name}: [Field; {length}] = {name}.serialize();\n'
            source += f'    for i in 0..{length} {{ assert(serialized_{name}[i] == prepared_payload[{offset} + i], "Field mapping mismatch"); }}\n'
        entry = 'try_settle_move_move' + ('_empty' if variant == 'empty' else '')
        for name, record in manifest['rawStateTransform']['states'].items():
            declaration = next(line for line in backend_functions[entry]['body'].splitlines()
                               if line.startswith('        let '+name+': '))
            def payload_word(match):
                index = int(match[1])
                assert 10 <= index < metadata['fields']+10
                return f'prepared_payload[{index-10}]'
            declaration = re.sub(r'prepared_payload\.words\[(\d+)\]', payload_word, declaration)
            declaration = declaration.replace('let '+name+': ', 'let raw_'+name+': ', 1)
            source += declaration+'\n'
            source += f'    assert(raw_{name} == serialized_{name}, "Raw state differs from original typed serialization");\n'
        transport = manifest['fieldBufferTransport']['entries'][variant]
        total = transport['backendFields']
        source += f'''    let buffer = FieldBuffer {{ words: prepared_payload }};
    assert(buffer.serialize() == prepared_payload, "System buffer changed a proved field");
    let addresses: [Field; 10] = [-1, -2, -3, -4, -5, -6, -7, -8, -9, -10];
    let expected_backend: [Field; {total}] = addresses.concat(buffer.serialize());
    let mut backend_calldata: [Field; {total+1}] = [0; {total+1}];
    backend_calldata[0] = 123456;
    for i in 0..10 {{ backend_calldata[i + 1] = addresses[i]; }}
    for field_index in 0..{width} {{
        backend_calldata[field_index + 11] = buffer.words[field_index];
    }}
    for i in 0..{total} {{ assert(backend_calldata[i + 1] == expected_backend[i], "Raw calldata differs from typed wire"); }}
    let mut backend_reader = Reader::new(expected_backend);
    let decoded_backend: FieldBuffer<{total}> = Deserialize::stream_deserialize(&mut backend_reader);
    backend_reader.finish();
    for i in 0..10 {{ assert(decoded_backend.words[i] == addresses[i], "Namespace prefix changed"); }}
    for i in 0..{width} {{ assert(decoded_backend.words[i + 10] == prepared_payload[i], "Backend payload offset changed"); }}
'''
        source += '}\n\n'
        leaves = sum((flatten_schema(schemas[item['name']]) for item in metadata['layout']), [])
        assert len(leaves) == width
        for pattern in ['zero', 'maximum', 'mixed']:
            source += f'#[test]\nunconstrained fn {variant}_{pattern}_roundtrip() {{\n'
            source += f'    roundtrip_{variant}({fixture(leaves, pattern)});\n}}\n\n'
    source += '''#[test]
unconstrained fn raw_late_event_patch_retains_every_tail_slot_and_timestamp() {
    for count in 1..21 {
        let mut typed = PlanetEvents::zero();
        typed.count = count;
        typed.last_updated = 18446744073709551615;
        for i in 0..20 { typed.events[i].id = -(i as Field) - 50; }
        let mut raw = typed.serialize();
        let event_id: Field = -1;
        typed.events[typed.count - 1].id = event_id;
        assert((raw[20] as u32) > 0);
        assert((raw[20] as u32) <= 20);
        raw[(raw[20] as u32) - 1] = event_id;
        assert(raw == typed.serialize(), "Late event patch changed another field");
    }
}
'''
    manifest = '''[package]
name = "move_payload_tests"
type = "lib"
authors = [""]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-nr", tag = "v5.0.1", directory = "aztec" }
types = { path = "../../../contracts/types" }
libs = { path = "../../../contracts/libs" }
'''
    return {'Nargo.toml': manifest, 'src/lib.nr': source}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    for name, expected in generate().items():
        target = DEST / name
        if args.write:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(expected)
        else:
            assert target.read_text() == expected, f'Stale decoder tests: {target}'
    print('PASS: seven decoder/raw-state tests exactly match the current prepared payload and original ABI schema')


if __name__ == '__main__':
    main()
