[package]
name = "game_state_backend"
type = "contract"
authors = [""]
[dependencies]
aztec = { path = "../../vendor/aztec" }
types = { path="../types" }
libs = { path="../libs" }
config = { path="../config" }
state_facade_interface = { path="../state_facade_interface" }
