[package]
name = "arrival"
type = "contract"
authors = [""]

[dependencies]
aztec = { path = "../../../vendor/aztec" }
types = { path = "../../types" }

libs = { path = "../../libs" }
game_state_backend = { path = "../../state_backend" }
state_backend_readonly = { path = "../../state_backend_readonly" }
